1
SELECT * FROM DEPARTMENT
WHERE DESCRIP IS NOT NULL;

2
SELECT PAPER.PANUM, PAPER.TITLE
FROM PAPER, AUTHOR 
WHERE AUTHOR.ACNUM = 100 AND PAPER.PANUM = AUTHOR.PANUM;

3
SELECT ACADEMIC.ACNUM, ACADEMIC.GIVENAME, ACADEMIC.FAMNAME, COUNT(AUTHOR.PANUM)
FROM ACADEMIC LEFT OUTER JOIN AUTHOR ON ACADEMIC.ACNUM = AUTHOR.ACNUM
GROUP BY ACADEMIC.ACNUM, ACADEMIC.GIVENAME, ACADEMIC.FAMNAME;

4
SELECT FIELD.ID, COUNT(INTEREST.ACNUM)
FROM FIELD, INTEREST
WHERE (ID LIKE '_.1.%' OR TRIM(ID) LIKE '_.1') AND FIELD.FIELDNUM = INTEREST.FIELDNUM
GROUP BY ID;

5
SELECT DEPTNUM, DEPTNAME, INSTNAME
FROM DEPARTMENT
WHERE DEPTNUM IN 
	(SELECT DEPTNUM
	FROM ACADEMIC
	WHERE ACNUM NOT IN 
		(SELECT ACNUM 
		FROM INTEREST));
		
6
SELECT ACNUM, FAMNAME, GIVENAME, ACADEMIC.DEPTNUM, DESCRIP
FROM ACADEMIC, DEPARTMENT
WHERE ACADEMIC.DEPTNUM = DEPARTMENT.DEPTNUM AND FAMNAME LIKE 'C%'
ORDER BY FAMNAME, GIVENAME, DEPTNUM, DESCRIP;

7
SELECT INTEREST.FIELDNUM, TITLE, COUNT(ACNUM) AS "NO. ACADEMICS INTERESTED"
FROM INTEREST, FIELD
WHERE FIELD.FIELDNUM = INTEREST.FIELDNUM
GROUP BY INTEREST.FIELDNUM, TITLE
ORDER BY INTEREST.FIELDNUM;

8
select department.instname, department.deptname, count(distinct(academic.acnum))
from department, academic, author
where department.deptnum = academic.deptnum and author.acnum = academic.acnum
having count(distinct(academic.acnum)) > 9
group by department.instname, department.deptname;

9
SELECT DEPTNUM
FROM DEPARTMENT
WHERE POSTCODE BETWEEN 3000 AND 3999
MINUS
SELECT DISTINCT(DEPTNUM)
FROM ACADEMIC
WHERE TRIM(TITLE) LIKE 'Prof%';

10
SELECT DEPTNUM, DEPTNAME
FROM DEPARTMENT
WHERE DEPTNUM IN (
	SELECT DEPTNUM
	FROM ACADEMIC, AUTHOR
	WHERE ACADEMIC.ACNUM = AUTHOR.ACNUM
	HAVING COUNT(DISTINCT PANUM) > 10
	GROUP BY DEPTNUM)
ORDER BY DEPTNUM, DEPTNAME;

11
select deptnum, deptname
from department
where deptnum in (
	select deptnum
	from academic
	minus
	select deptnum
	from academic, author
	where author.acnum = academic.acnum);
	
12
SELECT DISTINCT(PANUM)
FROM AUTHOR
WHERE EXISTS(
	SELECT *
	FROM ACADEMIC
	WHERE AUTHOR.ACNUM = ACADEMIC.ACNUM AND ACADEMIC.ACNUM IN(
		SELECT ACNUM
		FROM INTEREST, FIELD
		WHERE INTEREST.FIELDNUM = FIELD.FIELDNUM AND LOWER(FIELD.TITLE) LIKE '%data%' ));
		
13
SELECT FIELD.FIELDNUM, ID, TITLE, COUNT(ACNUM) AS "TOTAL NUMBER OF INTERESTED ACADEMICS"
FROM INTEREST, FIELD
WHERE INTEREST.FIELDNUM = FIELD.FIELDNUM
GROUP BY FIELD.FIELDNUM, ID, TITLE
HAVING COUNT(ACNUM) >= ALL(
	SELECT COUNT(ACNUM)
	FROM INTEREST, FIELD
	WHERE INTEREST.FIELDNUM = FIELD.FIELDNUM
	GROUP BY FIELD.FIELDNUM, ID, TITLE);